---
apiVersion: v1
data:
  certificado.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2VENDQTBPZ0F3SUJBZ0lTQmUrLy8zWGRpSjVKNVlMR0V2RktEWkdCTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpOVEFlRncweU5UQTBNVGt3TWpBek5EUmFGdzB5TlRBM01UZ3dNakF6TkROYU1CZ3hGakFVQmdOVkJBTVREV3QxClltVnlibVYwWlhNdWFXOHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVFc5YmVKaUd4TFR4UDgKdmV6UUpwNDlGWXNVWUhkOWNtbHg2b3A5anRoSi9saDJFZytjR2NlbnY5SkFFaUZvc0NQWm9hSGZ0bitkdDVDZApYd3Y1UjUyZG80SUNVVENDQWswd0RnWURWUjBQQVFIL0JBUURBZ2VBTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGCkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVEZEL0tTNENpaWtXZzgKYW4xZE4zTi94YzZvMFRBZkJnTlZIU01FR0RBV2dCU2ZLMS9QUENGUG5RUzM3U3NzeE1ad2k5TFhEVEJWQmdncgpCZ0VGQlFjQkFRUkpNRWN3SVFZSUt3WUJCUVVITUFHR0ZXaDBkSEE2THk5bE5TNXZMbXhsYm1OeUxtOXlaekFpCkJnZ3JCZ0VGQlFjd0FvWVdhSFIwY0RvdkwyVTFMbWt1YkdWdVkzSXViM0puTHpBckJnTlZIUkVFSkRBaWdnMXIKZFdKbGNtNWxkR1Z6TG1sdmdoRjNkM2N1YTNWaVpYSnVaWFJsY3k1cGJ6QVRCZ05WSFNBRUREQUtNQWdHQm1lQgpEQUVDQVRBc0JnTlZIUjhFSlRBak1DR2dINkFkaGh0b2RIUndPaTh2WlRVdVl5NXNaVzVqY2k1dmNtY3ZNaTVqCmNtd3dnZ0VGQmdvckJnRUVBZFo1QWdRQ0JJSDJCSUh6QVBFQWRnQ2tRc1VHU1dCaFZJOFAxT3FjKzNvdEprVk4KaDZsL0w5OUZXZlluVHpxRVZBQUFBWlpML3lZdUFBQUVBd0JITUVVQ0lRRERFOU5XMU5qUmFMOU9SZFR0akhKNgoxbkhQcC9KYVR6SHFMcnU0ZHN5TzJRSWdQMUVPMUt0aVViaXF6eUhWb2JKV3RVZmM4QzNXcXhRU0N4eUdyZzZvCkZnSUFkd0RNK3c5cWhYRUpaZjZWbTFQTzZiSjhJdW1GWEEyWGpiYXBmbFRBL2t3TnNBQUFBWlpML3laQkFBQUUKQXdCSU1FWUNJUUNBTXRNbUUxTVRrcGp6TThtZTVTWlZweExCMGNVclJzUS80dTlRcUJ6WThRSWhBT2thci9MWgptby9aTlR4UVJBQ2FyODNjaEM3YWM3LzFGTjNvaHh1SVl4bk9NQW9HQ0NxR1NNNDlCQU1EQTJnQU1HVUNNUUNZCkE3cE94U0dVaDVMaGRTbW9YQWVzUzlEN3l5STJ6ckR3K3VVTUt2Z0U4NXNsSUF5am1raC9YckdNZVNkUTNzMEMKTUVONDdoWFQwWnFDWXlUMzdLVzF2QXJVT3RDREJST20zTkQvT2txSXFwcVlNa0d1S2dWN0VFV1cvWEZCZGdXUwpEQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
kind: Secret
metadata:
  name: certificate
  namespace: dev
---
apiVersion: v1
data:
  #k create secret generic postgres --from-literal=DB_URL=postgresql://postgres:postgres@postgres.dev.svc.cluster.local:5432/postgres --dry-run=client -o yaml
  DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3Bvc3RncmVz
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  PGADMIN_DEFAULT_PASSWORD: cG9zdGdyZXM=
  PGADMIN_DEFAULT_EMAIL: ZG91Z2xhc0BkbmZjb3JwLmNvbS5icg==
kind: Secret
metadata:
  name: postgres
  namespace: dev