---
apiVersion: v1
data:
  certificado.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2VENDQTBPZ0F3SUJBZ0lTQmUrLy8zWGRpSjVKNVlMR0V2RktEWkdCTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpOVEFlRncweU5UQTBNVGt3TWpBek5EUmFGdzB5TlRBM01UZ3dNakF6TkROYU1CZ3hGakFVQmdOVkJBTVREV3QxClltVnlibVYwWlhNdWFXOHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVFc5YmVKaUd4TFR4UDgKdmV6UUpwNDlGWXNVWUhkOWNtbHg2b3A5anRoSi9saDJFZytjR2NlbnY5SkFFaUZvc0NQWm9hSGZ0bitkdDVDZApYd3Y1UjUyZG80SUNVVENDQWswd0RnWURWUjBQQVFIL0JBUURBZ2VBTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGCkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVEZEL0tTNENpaWtXZzgKYW4xZE4zTi94YzZvMFRBZkJnTlZIU01FR0RBV2dCU2ZLMS9QUENGUG5RUzM3U3NzeE1ad2k5TFhEVEJWQmdncgpCZ0VGQlFjQkFRUkpNRWN3SVFZSUt3WUJCUVVITUFHR0ZXaDBkSEE2THk5bE5TNXZMbXhsYm1OeUxtOXlaekFpCkJnZ3JCZ0VGQlFjd0FvWVdhSFIwY0RvdkwyVTFMbWt1YkdWdVkzSXViM0puTHpBckJnTlZIUkVFSkRBaWdnMXIKZFdKbGNtNWxkR1Z6TG1sdmdoRjNkM2N1YTNWaVpYSnVaWFJsY3k1cGJ6QVRCZ05WSFNBRUREQUtNQWdHQm1lQgpEQUVDQVRBc0JnTlZIUjhFSlRBak1DR2dINkFkaGh0b2RIUndPaTh2WlRVdVl5NXNaVzVqY2k1dmNtY3ZNaTVqCmNtd3dnZ0VGQmdvckJnRUVBZFo1QWdRQ0JJSDJCSUh6QVBFQWRnQ2tRc1VHU1dCaFZJOFAxT3FjKzNvdEprVk4KaDZsL0w5OUZXZlluVHpxRVZBQUFBWlpML3lZdUFBQUVBd0JITUVVQ0lRRERFOU5XMU5qUmFMOU9SZFR0akhKNgoxbkhQcC9KYVR6SHFMcnU0ZHN5TzJRSWdQMUVPMUt0aVViaXF6eUhWb2JKV3RVZmM4QzNXcXhRU0N4eUdyZzZvCkZnSUFkd0RNK3c5cWhYRUpaZjZWbTFQTzZiSjhJdW1GWEEyWGpiYXBmbFRBL2t3TnNBQUFBWlpML3laQkFBQUUKQXdCSU1FWUNJUUNBTXRNbUUxTVRrcGp6TThtZTVTWlZweExCMGNVclJzUS80dTlRcUJ6WThRSWhBT2thci9MWgptby9aTlR4UVJBQ2FyODNjaEM3YWM3LzFGTjNvaHh1SVl4bk9NQW9HQ0NxR1NNNDlCQU1EQTJnQU1HVUNNUUNZCkE3cE94U0dVaDVMaGRTbW9YQWVzUzlEN3l5STJ6ckR3K3VVTUt2Z0U4NXNsSUF5am1raC9YckdNZVNkUTNzMEMKTUVONDdoWFQwWnFDWXlUMzdLVzF2QXJVT3RDREJST20zTkQvT2txSXFwcVlNa0d1S2dWN0VFV1cvWEZCZGdXUwpEQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
kind: Secret
metadata:
  name: certificate
  namespace: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificate-conf
  namespace: dev
data:
  # file-like keys
  ca-certificates.conf: |
    # This file lists certificates that you wish to use or to ignore to be
    # installed in /etc/ssl/certs.
    # update-ca-certificates(8) will update /etc/ssl/certs by reading this file.
    #
    # This is autogenerated by dpkg-reconfigure ca-certificates.
    # Certificates should be installed under /usr/share/ca-certificates
    # and files with extension '.crt' is recognized as available certs.
    #
    # line begins with # is comment.
    # line begins with ! is certificate filename to be deselected.
    #
    mozilla/ACCVRAIZ1.crt
    mozilla/AC_RAIZ_FNMT-RCM.crt
    mozilla/AC_RAIZ_FNMT-RCM_SERVIDORES_SEGUROS.crt
    mozilla/ANF_Secure_Server_Root_CA.crt
    mozilla/Actalis_Authentication_Root_CA.crt
    mozilla/AffirmTrust_Commercial.crt
    mozilla/AffirmTrust_Networking.crt
    mozilla/AffirmTrust_Premium.crt
    mozilla/AffirmTrust_Premium_ECC.crt
    mozilla/Amazon_Root_CA_1.crt
    mozilla/Amazon_Root_CA_2.crt
    mozilla/Amazon_Root_CA_3.crt
    mozilla/Amazon_Root_CA_4.crt
    mozilla/Atos_TrustedRoot_2011.crt
    mozilla/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.crt
    mozilla/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068_2.crt
    mozilla/Baltimore_CyberTrust_Root.crt
    mozilla/Buypass_Class_2_Root_CA.crt
    mozilla/Buypass_Class_3_Root_CA.crt
    mozilla/CA_Disig_Root_R2.crt
    mozilla/CFCA_EV_ROOT.crt
    mozilla/COMODO_Certification_Authority.crt
    mozilla/COMODO_ECC_Certification_Authority.crt
    mozilla/COMODO_RSA_Certification_Authority.crt
    mozilla/Certainly_Root_E1.crt
    mozilla/Certainly_Root_R1.crt
    mozilla/Certigna.crt
    mozilla/Certigna_Root_CA.crt
    mozilla/Certum_EC-384_CA.crt
    mozilla/Certum_Trusted_Network_CA.crt
    mozilla/Certum_Trusted_Network_CA_2.crt
    mozilla/Certum_Trusted_Root_CA.crt
    mozilla/Comodo_AAA_Services_root.crt
    mozilla/D-TRUST_BR_Root_CA_1_2020.crt
    mozilla/D-TRUST_EV_Root_CA_1_2020.crt
    mozilla/D-TRUST_Root_Class_3_CA_2_2009.crt
    mozilla/D-TRUST_Root_Class_3_CA_2_EV_2009.crt
    mozilla/DigiCert_Assured_ID_Root_CA.crt
    mozilla/DigiCert_Assured_ID_Root_G2.crt
    mozilla/DigiCert_Assured_ID_Root_G3.crt
    mozilla/DigiCert_Global_Root_CA.crt
    mozilla/DigiCert_Global_Root_G2.crt
    mozilla/DigiCert_Global_Root_G3.crt
    mozilla/DigiCert_High_Assurance_EV_Root_CA.crt
    mozilla/DigiCert_TLS_ECC_P384_Root_G5.crt
    mozilla/DigiCert_TLS_RSA4096_Root_G5.crt
    mozilla/DigiCert_Trusted_Root_G4.crt
    mozilla/E-Tugra_Certification_Authority.crt
    mozilla/E-Tugra_Global_Root_CA_ECC_v3.crt
    mozilla/E-Tugra_Global_Root_CA_RSA_v3.crt
    mozilla/Entrust.net_Premium_2048_Secure_Server_CA.crt
    mozilla/Entrust_Root_Certification_Authority.crt
    mozilla/Entrust_Root_Certification_Authority_-_EC1.crt
    mozilla/Entrust_Root_Certification_Authority_-_G2.crt
    mozilla/Entrust_Root_Certification_Authority_-_G4.crt
    mozilla/GDCA_TrustAUTH_R5_ROOT.crt
    mozilla/GLOBALTRUST_2020.crt
    mozilla/GTS_Root_R1.crt
    mozilla/GTS_Root_R2.crt
    mozilla/GTS_Root_R3.crt
    mozilla/GTS_Root_R4.crt
    mozilla/GlobalSign_ECC_Root_CA_-_R4.crt
    mozilla/GlobalSign_ECC_Root_CA_-_R5.crt
    mozilla/GlobalSign_Root_CA.crt
    mozilla/GlobalSign_Root_CA_-_R3.crt
    mozilla/GlobalSign_Root_CA_-_R6.crt
    mozilla/GlobalSign_Root_E46.crt
    mozilla/GlobalSign_Root_R46.crt
    mozilla/Go_Daddy_Class_2_CA.crt
    mozilla/Go_Daddy_Root_Certificate_Authority_-_G2.crt
    mozilla/HARICA_TLS_ECC_Root_CA_2021.crt
    mozilla/HARICA_TLS_RSA_Root_CA_2021.crt
    mozilla/Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.crt
    mozilla/Hellenic_Academic_and_Research_Institutions_RootCA_2015.crt
    mozilla/HiPKI_Root_CA_-_G1.crt
    mozilla/Hongkong_Post_Root_CA_1.crt
    mozilla/Hongkong_Post_Root_CA_3.crt
    mozilla/ISRG_Root_X1.crt
    mozilla/ISRG_Root_X2.crt
    mozilla/IdenTrust_Commercial_Root_CA_1.crt
    mozilla/IdenTrust_Public_Sector_Root_CA_1.crt
    mozilla/Izenpe.com.crt
    mozilla/Microsec_e-Szigno_Root_CA_2009.crt
    mozilla/Microsoft_ECC_Root_Certificate_Authority_2017.crt
    mozilla/Microsoft_RSA_Root_Certificate_Authority_2017.crt
    mozilla/NAVER_Global_Root_Certification_Authority.crt
    mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt
    mozilla/OISTE_WISeKey_Global_Root_GB_CA.crt
    mozilla/OISTE_WISeKey_Global_Root_GC_CA.crt
    mozilla/QuoVadis_Root_CA_1_G3.crt
    mozilla/QuoVadis_Root_CA_2.crt
    mozilla/QuoVadis_Root_CA_2_G3.crt
    mozilla/QuoVadis_Root_CA_3.crt
    mozilla/QuoVadis_Root_CA_3_G3.crt
    mozilla/SSL.com_EV_Root_Certification_Authority_ECC.crt
    mozilla/SSL.com_EV_Root_Certification_Authority_RSA_R2.crt
    mozilla/SSL.com_Root_Certification_Authority_ECC.crt
    mozilla/SSL.com_Root_Certification_Authority_RSA.crt
    mozilla/SZAFIR_ROOT_CA2.crt
    mozilla/SecureSign_RootCA11.crt
    mozilla/SecureTrust_CA.crt
    mozilla/Secure_Global_CA.crt
    mozilla/Security_Communication_ECC_RootCA1.crt
    mozilla/Security_Communication_RootCA2.crt
    mozilla/Security_Communication_RootCA3.crt
    mozilla/Security_Communication_Root_CA.crt
    mozilla/Starfield_Class_2_CA.crt
    mozilla/Starfield_Root_Certificate_Authority_-_G2.crt
    mozilla/Starfield_Services_Root_Certificate_Authority_-_G2.crt
    mozilla/SwissSign_Gold_CA_-_G2.crt
    mozilla/SwissSign_Silver_CA_-_G2.crt
    mozilla/T-TeleSec_GlobalRoot_Class_2.crt
    mozilla/T-TeleSec_GlobalRoot_Class_3.crt
    mozilla/TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.crt
    mozilla/TWCA_Global_Root_CA.crt
    mozilla/TWCA_Root_Certification_Authority.crt
    mozilla/TeliaSonera_Root_CA_v1.crt
    mozilla/Telia_Root_CA_v2.crt
    mozilla/TrustCor_ECA-1.crt
    mozilla/TrustCor_RootCert_CA-1.crt
    mozilla/TrustCor_RootCert_CA-2.crt
    mozilla/Trustwave_Global_Certification_Authority.crt
    mozilla/Trustwave_Global_ECC_P256_Certification_Authority.crt
    mozilla/Trustwave_Global_ECC_P384_Certification_Authority.crt
    mozilla/TunTrust_Root_CA.crt
    mozilla/UCA_Extended_Validation_Root.crt
    mozilla/UCA_Global_G2_Root.crt
    mozilla/USERTrust_ECC_Certification_Authority.crt
    mozilla/USERTrust_RSA_Certification_Authority.crt
    mozilla/XRamp_Global_CA_Root.crt
    mozilla/certSIGN_ROOT_CA.crt
    mozilla/certSIGN_Root_CA_G2.crta
    mozilla/e-Szigno_Root_CA_2017.crt
    mozilla/ePKI_Root_Certification_Authority.crt
    mozilla/emSign_ECC_Root_CA_-_C3.crt
    mozilla/emSign_ECC_Root_CA_-_G3.crt
    mozilla/emSign_Root_CA_-_C1.crt
    mozilla/emSign_Root_CA_-_G1.crt
    mozilla/vTrus_ECC_Root_CA.crt
    mozilla/vTrus_Root_CA.crt  
    custom/certificado.crt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pycrud
  name: pycrud
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pycrud
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pycrud

    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: certificate 
        - name: certificate-conf
          configMap:
            name: certificate-conf
            items:
            - key: "ca-certificates.conf"
              path: "ca-certificates.conf"
      containers:
      - image: doug2901/pycrud:1.0.4
        imagePullPolicy: Always
        name: pycrud
        #openssl x509 -in /etc/ssl/certs/certificado.pem -noout -subject
        command: ["sh", "-c", "sudo update-ca-certificates --verbose && python3 -m flask run --host=0.0.0.0"]
        #command: ["sh", "-c", "update-ca-certificates --verbose && python3 -m flask run --host=0.0.0.0"]
#        args:
#          - |
#            cp /etc/custom-certs/ca-certificates.conf /etc/ca-certificates.conf && exec python app.py

        volumeMounts:
        - mountPath: /usr/share/ca-certificates/custom/
          name: secret-volume
          readOnly: true
        - mountPath: "/etc/ca-certificates.conf"
          subPath: ca-certificates.conf
          name: certificate-conf
          readOnly: true
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_URL
          value: "postgresql://postgres:postgres@postgres.dev.svc.cluster.local:5432/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: pycrud
  namespace: dev
  labels:
    app: pycrud
spec:
  selector:
    app: pycrud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: ClusterIP