apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pycrud-route
  namespace: dev
spec:
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: pycrud
        port:
          number: 80