---
apiVersion: v1
data:
  DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3Bvc3RncmVz
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
{{- if .Values.pgadmin.enabled }}
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AY29ycC5jb20uYnI=
{{- end }}
kind: Secret
metadata:
  name: {{ include "pycrud.fullname" . }}-database
  namespace: {{ .Release.Namespace }}