---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pycrud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "pycrud.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "pycrud.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ include "pycrud.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "pycrud.fullname" . }}-database
              key: DB_URL
{{- if .Values.env }}
{{- toYaml .Values.env | nindent 8 }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "pycrud.fullname" . }}-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pycrud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "pycrud.fullname" . }}
spec:
  selector:
    app: {{ include "pycrud.fullname" . }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: ClusterIP