{{- if .Values.pgadmin.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy: {}
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: "{{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}"
        name: pgadmin4
        imagePullPolicy: {{ .Values.pgadmin.image.pullPolicy }}
        {{- with .Values.pgadmin.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ include "pycrud.fullname" . }}-database
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pycrud.fullname" . }}-database
              key: PGADMIN_DEFAULT_PASSWORD
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          valueFrom:
            configMapKeyRef:
              name: {{ include "pycrud.fullname" . }}-database
              key: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
        - name: PGADMIN_CONFIG_LOGIN_BANNER
          valueFrom:
            configMapKeyRef:
              name: {{ include "pycrud.fullname" . }}-database
              key: PGADMIN_CONFIG_LOGIN_BANNER
        - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "pycrud.fullname" . }}-database
              key: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
{{- end }}